# -*- coding: utf-8 -*-
"""S6_GenAI_Lab4_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJLOLk4xYz1CQKvCZ8X9HQTqYMFRDghq

Prachee Prasad, 381060

Lab 4: Build a simple question-answering chatbot using a pre-trained language model.
"""

# !pip install -q transformers torch

#import libraries

from transformers import pipeline

# Load a pre-trained QA pipeline
qa_pipeline = pipeline(
    "question-answering",
    model="distilbert-base-uncased-distilled-squad"
)

# Provide Context Paragraph
context = """
Generative AI refers to artificial intelligence systems that can generate text,
images, audio, or other data. These models are trained on large datasets and
learn patterns in the data to produce human-like responses. Popular examples
include ChatGPT, DALL·E, and Gemini. Generative AI is widely used in chatbots,
content creation, and code generation.
"""

question = "What is Generative AI used for?"

# get answer

result = qa_pipeline(
    question=question,
    context=context
)

print("Question:", question)
print("Answer:", result["answer"])
print("Confidence Score:", result["score"])

# interactive chatbot

while True:
    user_question = input("Ask a question (or type 'exit'): ")

    if user_question.lower() == "exit":
        print("Chatbot exited.")
        break

    response = qa_pipeline(
        question=user_question,
        context=context
    )

    print("Answer:", response["answer"])
    print()

